# Generated by Django 5.2.1 on 2025-05-19 08:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='absensi',
            name='dibuat_oleh',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='absensi',
            name='jenis_absensi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.jenisabsensi'),
        ),
        migrations.AddField(
            model_name='kelas',
            name='jurusan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.jurusan'),
        ),
        migrations.AddField(
            model_name='kelas',
            name='wali_kelas',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'guru'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kelas_diampu', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pelanggaran',
            name='dibuat_oleh',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pelanggaran',
            name='jenis_pelanggaran',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.jenispelanggaran'),
        ),
        migrations.AddField(
            model_name='siswa',
            name='jurusan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.jurusan'),
        ),
        migrations.AddField(
            model_name='siswa',
            name='kelas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.kelas'),
        ),
        migrations.AddField(
            model_name='pelanggaran',
            name='siswa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.siswa'),
        ),
        migrations.AddField(
            model_name='absensi',
            name='siswa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.siswa'),
        ),
        migrations.AddField(
            model_name='siswa',
            name='tahun_masuk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tahunajaran'),
        ),
    ]
